import { http } from './http'
export const api={
  login:(username:string,password:string)=>http.post('/auth/login',{username,password}),
  dashboard:()=>http.get('/dashboard/summary'),dashboardAnalytics:()=>http.get('/dashboard/analytics'),
  activities:(params={})=>http.get('/activities',{params}),activity:(id:number,params={})=>http.get(`/activities/${id}`,{params}),activityImage:(activityId:number,imageId:number)=>http.get(`/activities/${activityId}/images/${imageId}`,{responseType:'blob'}),updateActivity:(id:number,data:object)=>http.put(`/activities/${id}`,data),deleteActivity:(id:number)=>http.delete(`/activities/${id}`),deleteActivities:(ids:number[])=>http.delete('/activities/batch',{data:{ids}}),
  notes:(params={})=>http.get('/notes',{params}),note:(id:number)=>http.get(`/notes/${id}`),noteImage:(noteId:number,imageId:number)=>http.get(`/notes/${noteId}/images/${imageId}`,{responseType:'blob'}),updateNote:(id:number,data:object)=>http.put(`/notes/${id}`,data),reviewNote:(id:number,status:'APPROVED'|'REJECTED')=>http.post(`/notes/${id}/review`,{status}),deleteNotes:(ids:number[])=>http.delete('/notes/batch',{data:{ids}}),approveNotes:(ids:number[])=>http.post('/notes/batch/approve',{ids}),reExtractNote:(id:number)=>http.post(`/notes/${id}/re-extract`),createNoteActivity:(id:number,data:object)=>http.post(`/notes/${id}/activities`,data),
  tasks:()=>http.get('/tasks'),createTask:(data:object)=>http.post('/tasks/crawl',data),restartTask:(id:number)=>http.post(`/tasks/${id}/restart`),stopTask:(id:number)=>http.post(`/tasks/${id}/stop`),logs:(id:number)=>http.get(`/tasks/${id}/logs`),batchDeleteTasks:(ids:number[])=>http.delete('/tasks/batch',{data:{ids}}),
  duplicates:()=>http.get('/duplicates'),merge:(id:number,keep='a')=>http.post(`/duplicates/${id}/merge`,{keep}),ignore:(id:number)=>http.post(`/duplicates/${id}/ignore`),
  reports:()=>http.get('/reports'),generateReport:(data:object)=>http.post('/reports/generate',data),report:(id:number)=>http.get(`/reports/${id}`),downloadReport:(id:number,format:'md'|'xlsx')=>http.get(`/reports/${id}/download`,{params:{format},responseType:'blob'}),deleteReport:(id:number)=>http.delete(`/reports/${id}`),
  settings:(kind:string)=>http.get(`/settings/${kind}`),createSetting:(kind:string,data:object)=>http.post(`/settings/${kind}`,data),updateSetting:(kind:string,id:number,data:object)=>http.put(`/settings/${kind}/${id}`,data),deleteSetting:(kind:string,id:number)=>http.delete(`/settings/${kind}/${id}`),enrichBlogger:(id:number)=>http.post(`/settings/bloggers/${id}/enrich`),downloadBloggerTemplate:()=>http.get('/settings/bloggers/import-template',{responseType:'blob'}),importBloggers:(file:File)=>http.post('/settings/bloggers/import',file,{params:{filename:file.name},headers:{'Content-Type':'application/octet-stream'}}),testOpenCLI:()=>http.post('/settings/opencli/test',undefined,{skipAuthRedirect:true} as any),openXhsLogin:()=>http.post('/settings/opencli/open-login'),
  diagnosticsSnapshot:()=>http.get('/diagnostics/snapshot'),diagnosticsOpencli:()=>http.get('/diagnostics/opencli'),diagnosticsXhsLogin:()=>http.get('/diagnostics/xhs-login'),diagnosticsXhsPool:()=>http.get('/diagnostics/xhs-pool'),
  keywordGroups:(params={})=>http.get('/settings/keyword-groups',{params}),keywordGroup:(id:number)=>http.get(`/settings/keyword-groups/${id}`),createKeywordGroup:(data:object)=>http.post('/settings/keyword-groups',data),patchKeywordGroup:(id:number,data:object)=>http.patch(`/settings/keyword-groups/${id}`,data),updateKeywordGroupWords:(id:number,words:string[])=>http.put(`/settings/keyword-groups/${id}/words`,{words}),updateKeywordGroupCities:(id:number,cityCodes:string[])=>http.put(`/settings/keyword-groups/${id}/cities`,{city_codes:cityCodes}),deleteKeywordGroup:(id:number)=>http.delete(`/settings/keyword-groups/${id}`),
  bloggerGroups:()=>http.get('/settings/blogger-groups'),bloggerGroup:(id:number)=>http.get(`/settings/blogger-groups/${id}`),createBloggerGroup:(data:object)=>http.post('/settings/blogger-groups',data),updateBloggerGroupMembers:(id:number,bloggerIds:number[])=>http.put(`/settings/blogger-groups/${id}/members`,{blogger_ids:bloggerIds}),deleteBloggerGroup:(id:number)=>http.delete(`/settings/blogger-groups/${id}`),
  schedules:()=>http.get('/schedules'),createSchedule:(data:object)=>http.post('/schedules',data),updateSchedule:(id:number,data:object)=>http.put(`/schedules/${id}`,data),deleteSchedule:(id:number)=>http.delete(`/schedules/${id}`),
  systemConfig:()=>http.get('/settings/system-config'),updateSystemConfig:(data:object)=>http.put('/settings/system-config',data),
  xhsAccounts:()=>http.get('/xhs-accounts'),createXhsAccount:(data:object)=>http.post('/xhs-accounts',data),updateXhsAccount:(id:number,data:object)=>http.put(`/xhs-accounts/${id}`,data),deleteXhsAccount:(id:number)=>http.delete(`/xhs-accounts/${id}`),checkXhsAccountLogin:(id:number)=>http.post(`/xhs-accounts/${id}/check-login`),
  posterTemplates:()=>http.get('/settings/poster-templates'),posterTemplate:(id:number)=>http.get(`/settings/poster-templates/${id}`),createPosterTemplate:(data:object)=>http.post('/settings/poster-templates',data),updatePosterTemplate:(id:number,data:object)=>http.put(`/settings/poster-templates/${id}`,data),deletePosterTemplate:(id:number)=>http.delete(`/settings/poster-templates/${id}`),parsePosterFromImage:(file:File)=>http.post('/settings/poster-templates/parse-from-image',file,{params:{filename:file.name, name:''},headers:{'Content-Type':'application/octet-stream'}}),
  posterTasks:()=>http.get('/poster-tasks'),posterTask:(id:number)=>http.get(`/poster-tasks/${id}`),createPosterTask:(data:object)=>http.post('/poster-tasks',data),updatePosterTask:(id:number,data:object)=>http.put(`/poster-tasks/${id}`,data),deletePosterTask:(id:number)=>http.delete(`/poster-tasks/${id}`),posterCandidates:(params={})=>http.get('/poster-tasks/candidates',{params}),posterPreview:(id:number)=>http.get(`/poster-tasks/${id}/preview`),posterRender:(id:number)=>http.post(`/poster-tasks/${id}/render`),posterDownload:(id:number)=>http.get(`/poster-tasks/${id}/download`,{responseType:'blob'}),noteImages:(noteId:number)=>http.get(`/posters/note-images/${noteId}`),noteImageById:(imageId:number)=>http.get(`/posters/note-image-by-id/${imageId}`,{responseType:'blob'}),
}
