<script setup lang="ts">
import {Plus,Refresh,Search,View} from '@element-plus/icons-vue';import {onMounted,reactive,ref} from 'vue';import {ElMessage,ElMessageBox} from 'element-plus';import {api} from '@/api/client'
const rows=ref<any[]>([]),total=ref(0),dialog=ref(false),drawer=ref(false),detail=ref<any>({}),editing=ref<number>(),filters=reactive({city:'',status:'',page:1}),form=reactive<any>({name:'',city_code:'shanghai',start_time:'',end_time:'',location:'',price:'',type:'展览',source_url:'',summary:'',status:'RAW'})
async function load(){const r=await api.activities(filters);rows.value=r.data.data.items;total.value=r.data.pagination.total}
function open(row?:any){editing.value=row?.id;Object.assign(form,row||{name:'',city_code:'shanghai',start_time:'',end_time:'',location:'',price:'',type:'展览',source_url:'',summary:'',status:'RAW'});dialog.value=true}
async function save(){const data={...form,start_time:new Date(form.start_time).toISOString(),end_time:form.end_time?new Date(form.end_time).toISOString():null};editing.value?await api.updateActivity(editing.value,data):await api.createActivity(data);dialog.value=false;ElMessage.success('保存成功');load()}
async function remove(id:number){await ElMessageBox.confirm('确认删除该活动？','删除确认',{type:'warning'});await api.deleteActivity(id);ElMessage.success('已删除');load()}
async function show(id:number){detail.value=(await api.activity(id)).data.data;drawer.value=true}
onMounted(load)
</script>
<template><ElCard shadow="never" class="page-card"><div class="toolbar"><ElInput v-model="filters.city" placeholder="城市代码" clearable class="grow"/><ElSelect v-model="filters.status" placeholder="状态" clearable><ElOption v-for="s in ['RAW','NEEDS_REVIEW','APPROVED','PUBLISHED']" :key="s" :value="s"/></ElSelect><ElButton :icon="Search" @click="load">筛选</ElButton><ElButton :icon="Refresh" @click="Object.assign(filters,{city:'',status:''});load()">重置</ElButton><ElButton type="primary" :icon="Plus" @click="open()">新增活动</ElButton></div><ElTable :data="rows"><ElTableColumn prop="name" label="活动名称"/><ElTableColumn prop="city_code" label="城市" width="100"/><ElTableColumn prop="start_time" label="时间" width="190"/><ElTableColumn prop="location" label="地点"/><ElTableColumn prop="status" label="状态" width="130"><template #default="s"><ElTag>{{s.row.status}}</ElTag></template></ElTableColumn><ElTableColumn label="操作" width="220"><template #default="s"><ElButton text :icon="View" @click="show(s.row.id)">详情</ElButton><ElButton text type="primary" @click="open(s.row)">编辑</ElButton><ElButton text type="danger" @click="remove(s.row.id)">删除</ElButton></template></ElTableColumn></ElTable><ElPagination v-model:current-page="filters.page" :total="total" :page-size="20" layout="total, prev, pager, next" @current-change="load"/></ElCard><ElDialog v-model="dialog" :title="editing?'编辑活动':'新增活动'" width="640"><ElForm label-width="90"><ElFormItem label="名称"><ElInput v-model="form.name"/></ElFormItem><ElFormItem label="城市"><ElInput v-model="form.city_code"/></ElFormItem><ElFormItem label="时间"><ElDatePicker v-model="form.start_time" type="datetime"/><ElDatePicker v-model="form.end_time" type="datetime"/></ElFormItem><ElFormItem label="地点"><ElInput v-model="form.location"/></ElFormItem><ElFormItem label="费用"><ElInput v-model="form.price"/></ElFormItem><ElFormItem label="类型"><ElInput v-model="form.type"/></ElFormItem><ElFormItem label="状态"><ElSelect v-model="form.status"><ElOption v-for="s in ['RAW','NEEDS_REVIEW','APPROVED']" :key="s" :value="s"/></ElSelect></ElFormItem><ElFormItem label="来源"><ElInput v-model="form.source_url"/></ElFormItem><ElFormItem label="摘要"><ElInput v-model="form.summary" type="textarea"/></ElFormItem></ElForm><template #footer><ElButton @click="dialog=false">取消</ElButton><ElButton type="primary" @click="save">保存</ElButton></template></ElDialog><ElDrawer v-model="drawer" title="活动详情"><ElDescriptions :column="1" border><ElDescriptionsItem label="名称">{{detail.name}}</ElDescriptionsItem><ElDescriptionsItem label="时间">{{detail.start_time}}</ElDescriptionsItem><ElDescriptionsItem label="地点">{{detail.location}}</ElDescriptionsItem><ElDescriptionsItem label="费用">{{detail.price}}</ElDescriptionsItem><ElDescriptionsItem label="摘要">{{detail.summary}}</ElDescriptionsItem></ElDescriptions></ElDrawer></template>
